SET(TEST_LIST_SOURCES_FILES
	${CMAKE_CURRENT_LIST_DIR}/mrd_communication/i_mrd_communication.cpp
	${CMAKE_CURRENT_LIST_DIR}/mrd_communication/i_mrd_communication_wifi.cpp
	${CMAKE_CURRENT_LIST_DIR}/mrd_plugin/i_mrd_plugin.cpp
	${CMAKE_CURRENT_LIST_DIR}/mrd_plugin/i_mrd_plugin_ahrs.cpp
	${CMAKE_CURRENT_LIST_DIR}/mrd_plugin/i_mrd_plugin_eeprom.cpp
	${CMAKE_CURRENT_LIST_DIR}/mrd_plugin/i_mrd_plugin_gpio_in_out.cpp
	${CMAKE_CURRENT_LIST_DIR}/mrd_plugin/i_mrd_plugin_i2c.cpp
	${CMAKE_CURRENT_LIST_DIR}/mrd_plugin/i_mrd_plugin_joypad.cpp
	${CMAKE_CURRENT_LIST_DIR}/mrd_plugin/i_mrd_plugin_sd.cpp
	${CMAKE_CURRENT_LIST_DIR}/mrd_plugin/i_mrd_plugin_servo.cpp
)
